# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massa', models.CharField(max_length=10, verbose_name='Massa de cafe(g): ')),
                ('hexano', models.CharField(max_length=10, verbose_name='Volume de hexano utilizado')),
                ('oleo', models.CharField(max_length=10, verbose_name='Volume de oleo obtido(ml)')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da extracao')),
            ],
        ),
    ]
