# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='massa',
            field=models.CharField(max_length=10, verbose_name='Massa de cafe(g)'),
        ),
    ]
