# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dado', '0002_auto_20171025_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='data',
            field=models.DateTimeField(max_length=100, verbose_name='Data da extracao'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='hexano',
            field=models.FloatField(verbose_name='Volume de hexano utilizado'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='massa',
            field=models.FloatField(verbose_name='Massa de cafe(g)'),
        ),
        migrations.AlterField(
            model_name='dado',
            name='oleo',
            field=models.FloatField(verbose_name='Volume de oleo obtido(ml)'),
        ),
    ]
