# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dado', '0003_auto_20171106_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='relacao',
            field=models.TextField(default=0, max_length=100, verbose_name='Eficiencia da extracao(%): (Massa Cafe/84.6)'),
            preserve_default=False,
        ),
    ]
